// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAHb9_0HtYGJmJs2KCTgkR4gEb4QXJYRuo',
    appId: '1:823810980714:web:6e952855bd3555e42f0313',
    messagingSenderId: '823810980714',
    projectId: 'mind-e9eba',
    authDomain: 'mind-e9eba.firebaseapp.com',
    databaseURL: 'https://mind-e9eba-default-rtdb.firebaseio.com',
    storageBucket: 'mind-e9eba.appspot.com',
    measurementId: 'G-5TT053VT56',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAMvP1mu_1blHe6uK6R62hEpXmQN_VdG-Y',
    appId: '1:823810980714:android:5404c330835833952f0313',
    messagingSenderId: '823810980714',
    projectId: 'mind-e9eba',
    databaseURL: 'https://mind-e9eba-default-rtdb.firebaseio.com',
    storageBucket: 'mind-e9eba.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB12ivgwPsKJr1TV-PpyTwiRWAq-9rgnGM',
    appId: '1:823810980714:ios:58ef7b0634d0e8ae2f0313',
    messagingSenderId: '823810980714',
    projectId: 'mind-e9eba',
    databaseURL: 'https://mind-e9eba-default-rtdb.firebaseio.com',
    storageBucket: 'mind-e9eba.appspot.com',
    iosClientId: '823810980714-30n053b0q8jtpdb2jkd08c6hemp4joal.apps.googleusercontent.com',
    iosBundleId: 'com.example.mind',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB12ivgwPsKJr1TV-PpyTwiRWAq-9rgnGM',
    appId: '1:823810980714:ios:58ef7b0634d0e8ae2f0313',
    messagingSenderId: '823810980714',
    projectId: 'mind-e9eba',
    databaseURL: 'https://mind-e9eba-default-rtdb.firebaseio.com',
    storageBucket: 'mind-e9eba.appspot.com',
    iosClientId: '823810980714-30n053b0q8jtpdb2jkd08c6hemp4joal.apps.googleusercontent.com',
    iosBundleId: 'com.example.mind',
  );
}
